### ISSUE TITLE
to: Hamish

### ISSUE THREAD

**Issue by mikulabc** [hamarb123/hamarb123.github.io#1]
Here is how i got here :)
1. I got bored at 3am while trying to work but couldnt because of corona
2. Opened the Windows Store on Windows 10 and clicked on the "GAMING" tab
3. Saw "ROBLOX" which the thumbail seemed cool because it reminded me of LEGO
4. On the "ROBLOX" description page i scrolled down to see what other games were shown and i got intrigued by the weird thumbnail of simply green top and brown bottom, reminded me a bit of minecraft, so i clicked on that "2DCraft" i did not know what i was going to expect, something to craft?
5. I saw the screenshots and thought that this game was probably made by some teenager experimenting with the first games that can be put out there to the public and letting the creativity go without expecting anything probably
6. I then thought who this person might be, since i was just getting curious how i could also publish something on the windows store maybe, so i clicked on the "2DCraft privacy policy" and landed on https://hamarb123.github.io/privacypolicy.html from there i went to https://github.com/hamarb123 and then decided to post this ticket here because https://github.com/hamarb123/hamarb123.github.io was shown on the frontpage of your account

now... maybe you could actually really help me out here :) can you publish some app in the windows store that can help me manipulate text?

**Comment by mikulabc** [comment]
Oh and i have not yet downloaded the game because i got distracted again and closed the store

**Comment by hamarb123** [comment]
I have emailed you.
